language: node_js
node_js:
  - lts/*
install:
  - npm ci # npm ci
script:
  - sh ./deploy.sh # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $access_token # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: master